language: node_js
node_js:
  - "0.10"
install:
  - npm install -g grunt grunt-cli nodeunit istanbul
script:
  - npm run-script ci
env:
  global:
    - secure: "bUEh3g16VvB9TuB/p3/KG3jAYMuNjTaPptRIxmaf+bzft3bjHNbRdwd0LwEn4kuAngb/oZEpPXjSiLs+MGgRR6vF22NwFxzX6huYKz4FWC18xngOpO93Cz5W8SdixTXiDIXnWTKSQh6qOH8xhp4sN9GSE2T2+J41N7Z3Tz+ao9Q="
